# Generated by Django 3.1.7 on 2021-03-16 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('email', 'cursos')},
        ),
    ]
