# Generated by Django 3.1.7 on 2021-03-16 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20210316_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='cursos',
            new_name='curso',
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('email', 'curso')},
        ),
    ]
