# Generated by Django 3.1.7 on 2021-03-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_auto_20210316_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
