# Generated by Django 3.1.7 on 2021-03-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_auto_20210316_0220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['pk'], 'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['pk'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
